apiVersion: v1
kind: Service
metadata:
  name: nutrition
  labels:
    app: microrecipe
    service: nutrition
spec:
  selector:
    app: microrecipe
    service: nutrition
  ports:
    - name: http-port
      port: 3000
    - name: grpc
      port: 5000
    - name: tcp-microservice
      port: 5001
