apiVersion: v1
kind: Service
metadata:
  name: recipe
  labels:
    app: microrecipe
    service: recipe
spec:
  selector:
    app: microrecipe
    service: recipe
  ports:
    - name: http-port
      port: 3000
    - name: grpc
      port: 5000
