apiVersion: v1
kind: Service
metadata:
  name: ingridient
  labels:
    app: microrecipe
    service: ingridient
spec:
  selector:
    app: microrecipe
    service: ingridient
  ports:
    - name: http-port
      port: 3000
    - name: grpc
      port: 5000
    - name: tcp-microservice
      port: 5001
