version: '2'

services:
  proxy:
    build:
      context: ./proxy
    ports:
      - 81:80

  recipes:
    build:
      context: ../../../recipe
      dockerfile: dev.Dockerfile
    volumes:
      - ../../../recipe/src:/app/src
    env_file: .env

  ingridients:
    build:
      context: ../../../ingridient
      dockerfile: dev.Dockerfile
    volumes:
      - ../../../ingridient/src:/app/src
    env_file: .env

  nutritions:
    build:
      context: ../../../nutrition
      dockerfile: dev.Dockerfile
    volumes:
      - ../../../nutrition/src:/app/src
    env_file: .env
